<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>9.0</LangVersion>
		<Nullable>enable</Nullable>
		<RootNamespace>DvMod.RemoteDispatch</RootNamespace>
		<InformationalVersion>1.6.1</InformationalVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Krafs.Publicizer" Version="2.2.1" />
		<PackageReference Include="Lib.Harmony" Version="2.4.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<Publicize Include="Assembly-CSharp" IncludeCompilerGeneratedMembers="false" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/Assembly-CSharp.dll" />
		<Reference Include="DV.BrakeSystem" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/DV.BrakeSystem.dll" />
		<Reference Include="DV.Simulation" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/DV.Simulation.dll" />
		<Reference Include="DV.Common" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/DV.Common.dll" />
		<Reference Include="DV.Interaction" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/DV.Interaction.dll" />
		<Reference Include="DV.PointSet" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/DV.PointSet.dll" />
		<Reference Include="DV.RailTrack" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/DV.RailTrack.dll" />
		<Reference Include="DV.ThingTypes" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/DV.ThingTypes.dll" />
		<Reference Include="DV.Utils" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/DV.Utils.dll" />
		<Reference Include="Microsoft.CSharp" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/Microsoft.CSharp.dll" />
		<Reference Include="Newtonsoft.Json" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/Newtonsoft.Json.dll" />
		<Reference Include="net.smkd.vector3d" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/net.smkd.vector3d.dll" />
		<Reference Include="WorldStreamer" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/WorldStreamer.dll" />
		<Reference Include="Facepunch.Steamworks.Win64" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/Facepunch.Steamworks.Win64.dll" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="UnityEngine.CoreModule" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/UnityEngine.CoreModule.dll" />
		<Reference Include="UnityEngine.IMGUIModule" HintPath="/home/rass/.local/share/Steam/steamapps/common/Derail Valley/DerailValley_Data/Managed/UnityEngine.IMGUIModule.dll" />
		<PackageReference Include="UnityModManager" Version="0.27.2" />
	</ItemGroup>

	

	<ItemGroup>
		<EmbeddedResource Include="frontend/icon.svg" />
		<EmbeddedResource Include="frontend/index.html" />
		<EmbeddedResource Include="frontend/*.js" />
		<EmbeddedResource Include="frontend/style.css" />
		<EmbeddedResource Include="frontend/licenses/*.png" />
		<EmbeddedResource Include="frontend/signals/*.webp" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(OS)' == 'Windows_NT'">
		<!-- Drop the output DLL into the root build\ folder -->
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildThisFileDirectory)..\build\" />
	</Target>
</Project>
